#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTipper,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//--------------------------------------
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
//--------------------------------------
void driveControlR(int leftDrive, int rightDrive)
{
	motor[leftSideDrive] = leftDrive;
	motor[rightSideDrive] = rightDrive;
}
//--------------------------------------
//Wait for Press
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}

//Wait for Release
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//--------------------------------------
task main()
{
	int count = 0;

	clearLCDLine(0);
	clearLCDLine(1);

	while(nLCDButtons != centerButton)
	{
		switch(count)
		{
		case 0:
			displayLCDCenteredString(0, "10 pt + Tip");
			displayLCDCenteredString(1, "<   Select   >");
			waitForPress();

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			displayLCDCenteredString(0, "20 pt");
			displayLCDCenteredString(1, "<   Select   >");
			waitForPress();

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			displayLCDCenteredString(0, "Stay still");
			displayLCDCenteredString(1, "<   Select   >");
			waitForPress();

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
	clearLCDLine(0);
	clearLCDLine(1);

	switch(count){
	case 0:

		displayLCDCenteredString(0, "10 pt + tip");
		displayLCDCenteredString(1, "is running.");
		wait1Msec(2000);

		while(1==1)
		{
			clearLCDLine(0);
			clearLCDLine(1);
			motor[leftSideDrive] = vexRT[Ch3];
			motor[rightSideDrive] = vexRT[Ch2];

			if(vexRT[Btn6U] == 1)
			{
				motor[rightMobileGoal] = -127;
				motor[leftMobileGoal] = -127;
			}
			else if(vexRT[Btn6D] == 1)
			{
				motor[rightMobileGoal] = 127;
				motor[leftMobileGoal] = 127;
			}
			else
			{
				motor[rightMobileGoal] = 0;
				motor[leftMobileGoal] = 0;
			}
			if(vexRT[Btn5U] == 1)
			{
				motor[rightTipper] = -63;
				motor[leftTipper] = -63;
			}
			else if(vexRT[Btn5D] == 1)
			{
				motor[rightTipper] = 63;
				motor[leftTipper] = 63;
			}
			else
			{
				motor[rightTipper] = 0;
				motor[leftTipper] = 0;
			}

		}


	}
}
